### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by luongcongtandpt** [Hahaa13/java2bedrock.sh#192]
### Conversion Issue Link

https://github.com/Hahaa13/java2bedrock.sh/actions/runs/5829405354

### Expected Output

Convert error

### Actual Output

How tf to fix this bruhhh

**Comment by Hahaa13** [comment]
Nếu bạn sử dụng dropbox thì set ở cuối link dl=0 thành dl=1 dùm

**Comment by luongcongtandpt** [comment]
> Nếu bạn sử dụng dropbox thì set ở cuối link dl=0 thành dl=1 dùm

![image](https://github.com/Hahaa13/java2bedrock.sh/assets/137200888/c1f0c8ec-39af-4f39-8b11-62fcf3ddbb1f)
lại bị dính lỗi này ạ :V

**Comment by Hahaa13** [comment]
tắt protection của itemsadder
