### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by luongcongtandpt** [Hahaa13/java2bedrock.sh#213]
### Conversion Issue Link

https://github.com/Hahaa13/java2bedrock.sh/actions/runs/5840565585

### Expected Output

Geysermapping don't have anything inside

### Actual Output

Hi ,after convert , geyser_mapping.json files don't have anything inside . did i do sth wrong or my pack is error

### Additional Context

Pls help me , did i do sthing wrong
![image](https://github.com/Hahaa13/java2bedrock.sh/assets/137200888/3fb6e85e-00b0-489d-91f3-f8e41ea129d3)

**Comment by Hahaa13** [comment]
Lên json format check sprites.json
