### ISSUE TITLE
Lỗi mất model part mob 3D

### ISSUE THREAD

**Issue by luongcongtandpt** [Hahaa13/java2bedrock.sh#219]
### Conversion Issue Link

https://github.com/Hahaa13/java2bedrock.sh/actions/runs/5840565585

### Expected Output

Lỗi này có fix đượic không nhỉ

### Actual Output

Mình convert mob model engine bị mất part , đầu chân lẫn lộn :v

**Comment by Hahaa13** [comment]
Này không giúp đc r hết cứu nên quan repo góc mà hỏi
